xcopy /y/s C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\css \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\css
xcopy /y/s C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\fonts \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\fonts
xcopy /y/s C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\images \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\images
xcopy /y/s C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\js \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\js
xcopy /y C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\index.html \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\index.html
xcopy /y C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\cudovit-dan.html \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\cudovit-dan.html
xcopy /y C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\nadaljevanje-lepe-zgodbe.html \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\nadaljevanje-lepe-zgodbe.html
xcopy /y C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\polne-baterije.html \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\polne-baterije.html
xcopy /y C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\sladko-zivljenje.html \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\sladko-zivljenje.html
xcopy /y C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\zabavna-presenecenja.html \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\zabavna-presenecenja.html
xcopy /y C:\Users\Rok\Dropbox\Petra\Poroka\Obljubiva.si\stran\favicon.ico \\VS-WEB\C$\inetpub\wwwroot\RokPoroka\favicon.ico